plugins {
    alias(libs.plugins.detekt)
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.multiplatform) apply false
    alias(libs.plugins.android.kotlin.multiplatform.library) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.jetbrains.compose) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.androidx.room) apply false
    alias(libs.plugins.aboutlibraries) apply false
    alias(libs.plugins.spring.boot) apply false
    alias(libs.plugins.spring.dependency.management) apply false
    alias(libs.plugins.kotlin.spring) apply false
    alias(libs.plugins.kotlin.jpa) apply false
    alias(libs.plugins.dokka) apply false
}

// Project-wide kotlinx-datetime alignment (single source — covers :app, :desktopApp and every library). Every
// `Clock.System.now()` / `kotlinx.datetime.Instant` call site (e.g. `AideMessage.createdAt`) compiles against
// datetime 0.6.2, whose `kotlinx.datetime.{Clock,Instant}` are real classes. datetime 0.7.x MOVED both
// to `kotlin.time` and DROPPED the old classes, so a 0.7.x runtime throws `NoClassDefFoundError kotlinx.datetime
// .Instant` / `Clock$System`. compose-material3's *desktop* artifact requests 0.7.1; without this force
// :desktopApp's runtime classpath upgrades to it. Pin EVERY module to 0.6.2 to match the compiled bytecode.
// `kotlin.time` + datetime 0.7.x is now purely our call.)
val datetimeForce = "${libs.kotlinx.datetime.get().module}:${libs.kotlinx.datetime.get().versionConstraint.requiredVersion}"
allprojects {
    configurations.all {
        resolutionStrategy { force(datetimeForce) }
    }
}
// ----------------------------------------------------------------------------------------------------------
// `./gradlew moduleGraph` (or `make graph`) → docs/module-graph.md, a Mermaid rendering of the actual
// project-to-project dependencies. The modularization guardrail from the target-architecture doc: a generated
// graph is the cheapest guard against layering drift, and it is what replaced the old LayeringRulesTest.
// Reads DECLARED dependencies (no configuration resolution), so it works for the KMP modules too.
val moduleGraph = tasks.register("moduleGraph") {
    group = "documentation"
    description = "Regenerates docs/module-graph.md from the projects' declared dependencies."
    notCompatibleWithConfigurationCache("reads every module's declared project dependencies")
    val output = layout.projectDirectory.file("docs/module-graph.md").asFile
    val edges = provider {
        subprojects
            // Skip the path-only container projects (":core", ":data:speech") — they have no build file
            // and exist only because their children are nested under them.
            .filter { it.buildFile.exists() }
            .sortedBy { it.path }
            .map { sub ->
                sub.path to sub.configurations
                    .flatMap { conf -> conf.dependencies.withType(ProjectDependency::class.java) }
                    .map { it.path }
                    // The KMP/AGP plugins add a self-reference to some configurations; it is not an edge.
                    .filter { it != sub.path }
                    .distinct()
                    .sorted()
            }
    }
    outputs.file(output)
    // These read the source tree itself, not a declared input set — always regenerate rather than report a
    // stale map as up-to-date.
    outputs.upToDateWhen { false }
    doLast {
        val lines = buildString {
            appendLine("# Module graph")
            appendLine()
            appendLine("Generated by `./gradlew moduleGraph` — do not edit by hand. Every arrow points from a")
            appendLine("module to something it depends on; see ARCHITECTURE.md §2 for what the direction means.")
            appendLine()
            appendLine("```mermaid")
            appendLine("graph TD")
            edges.get().forEach { (path, deps) ->
                if (deps.isEmpty()) appendLine("  ${path.nodeId()}[\"$path\"]")
                deps.forEach { dep -> appendLine("  ${path.nodeId()}[\"$path\"] --> ${dep.nodeId()}[\"$dep\"]") }
            }
            appendLine("```")
        }
        output.parentFile.mkdirs()
        output.writeText(lines)
        logger.lifecycle("Wrote ${output.relativeTo(rootDir)}")
    }
}

fun String.nodeId(): String = trimStart(':').replace(':', '_').replace('-', '_')

// ----------------------------------------------------------------------------------------------------------
// The package audit. `./gradlew codeMap` (or `make map`) renders it as docs/code-map.md — which module holds
// which Kotlin package, plus the reverse lookup. `codeMapCheck` (wired into `make check`) is the enforcement
// half: it fails the build on any of the three ways "an import names its module" can stop being true.
//
// It reads the `package` declaration out of each file rather than inferring one from the folder, because a
// file whose declared package disagrees with its folder is exactly the case a path-derived audit cannot see.

// Modules whose package root deliberately differs from their Gradle path.
val packageRootOverrides = mapOf(
    ":desktopApp" to "com.sabreware.aide.desktop",
)

// Files that deliberately declare a package outside our root, keyed by repo-relative path. The one resident
// is a desktop stand-in for an Android framework class the Sherpa JNI surface names; it has to carry that
// class's package or the linkage does not work.
val foreignPackageAllowlist = setOf(
    "data/speech/sherpa/src/desktopMain/kotlin/android/content/res/AssetManager.kt",
)

/** `:core:designsystem` -> `com.sabreware.aide.core.designsystem`; the invariant this whole audit is about. */
fun expectedPackageRoot(modulePath: String): String =
    packageRootOverrides[modulePath]
        ?: modulePath.trimStart(':').split(':').joinToString(
            separator = ".",
            prefix = "com.sabreware.aide.",
        )

/** One Kotlin source file, as the audit sees it. */
class SourceFile(
    val module: String,
    val relativePath: String,
    val declared: String?,
    val byDirectory: String?,
)

/**
 * Every Kotlin file under every module's `src`, with the package it declares and the package its directory
 * implies. Both are nullable: a file with no `package` line (root package) and a file outside any
 * `.../kotlin/` root are both real and both simply drop out of the checks that need the missing half.
 */
fun Project.sourceFiles(): List<SourceFile> {
    val packageLine = Regex("""^\s*package\s+([A-Za-z_][\w.`]*)""")
    // `src/<sourceSet>/<kotlin|java>/<package path>/File.kt` — the segment after the source-set root is what
    // the directory claims the package is.
    val sourceRoot = Regex("""/src/[^/]+/(?:kotlin|java)/""")
    return subprojects
        .filter { it.buildFile.exists() }
        .sortedBy { it.path }
        .flatMap { sub ->
            val src = File(sub.projectDir, "src")
            if (!src.isDirectory) return@flatMap emptyList<SourceFile>()
            src.walkTopDown()
                .filter { it.isFile && it.extension == "kt" }
                .map { file ->
                    val relative = file.relativeTo(rootDir).invariantSeparatorsPath
                    val declared = file.useLines { lines ->
                        lines.firstNotNullOfOrNull { packageLine.find(it)?.groupValues?.get(1) }
                    }?.replace("`", "")
                    val afterRoot = sourceRoot.find(file.invariantSeparatorsPath)?.let {
                        file.invariantSeparatorsPath.substring(it.range.last + 1)
                    }
                    val byDirectory = afterRoot
                        ?.substringBeforeLast('/', missingDelimiterValue = "")
                        ?.takeIf { it.isNotEmpty() }
                        ?.replace('/', '.')
                    SourceFile(sub.path, relative, declared, byDirectory)
                }
                .toList()
        }
}

/** The three ways the invariant breaks, each rendered as a ready-to-print line. */
class PackageAudit(
    val split: Map<String, Set<String>>,
    val misplaced: List<String>,
    val strayed: List<String>,
) {
    val isClean: Boolean get() = split.isEmpty() && misplaced.isEmpty() && strayed.isEmpty()
}

fun Project.auditPackages(files: List<SourceFile>): PackageAudit {
    val byPackage = sortedMapOf<String, MutableSet<String>>()
    val misplaced = mutableListOf<String>()
    val strayed = mutableListOf<String>()

    files.forEach { f ->
        val declared = f.declared ?: return@forEach
        byPackage.getOrPut(declared) { sortedSetOf() }.add(f.module)

        if (f.relativePath !in foreignPackageAllowlist) {
            val root = expectedPackageRoot(f.module)
            if (declared != root && !declared.startsWith("$root.")) {
                misplaced += "${f.relativePath}: declares `$declared`, but ${f.module} owns `$root.*`"
            }
        }
        val byDirectory = f.byDirectory
        if (byDirectory != null && byDirectory != declared) {
            strayed += "${f.relativePath}: declares `$declared`, but its directory says `$byDirectory`"
        }
    }
    return PackageAudit(byPackage.filterValues { it.size > 1 }, misplaced, strayed)
}

val codeMap = tasks.register("codeMap") {
    group = "documentation"
    description = "Regenerates docs/code-map.md: package -> module index across the whole tree."
    notCompatibleWithConfigurationCache("walks every module's source tree")
    val output = layout.projectDirectory.file("docs/code-map.md").asFile
    val files = provider { rootProject.sourceFiles() }
    outputs.file(output)
    // Reads the source tree itself, not a declared input set — always regenerate rather than report a stale
    // map as up-to-date.
    outputs.upToDateWhen { false }
    doLast {
        val all = files.get()
        val pkgToModules = sortedMapOf<String, MutableSet<String>>()
        val modulePkgs = sortedMapOf<String, MutableSet<String>>()
        val moduleFiles = sortedMapOf<String, Int>()
        all.forEach { f ->
            val pkg = f.declared ?: return@forEach
            pkgToModules.getOrPut(pkg) { sortedSetOf() }.add(f.module)
            modulePkgs.getOrPut(f.module) { sortedSetOf() }.add(pkg)
            moduleFiles[f.module] = (moduleFiles[f.module] ?: 0) + 1
        }
        val shared = pkgToModules.filterValues { it.size > 1 }
        val text = buildString {
            appendLine("# Code map — which module holds which package")
            appendLine()
            appendLine("Generated by `./gradlew codeMap` — do not edit by hand.")
            appendLine()
            appendLine("Package path mirrors module path, so an import already names its module. This is the index")
            appendLine("that proves it: the split-packages section must stay empty. Packages here are read from each")
            appendLine("file's `package` declaration, not from its folder. See")
            appendLine("[module-graph.md](module-graph.md) for how the modules depend on each other, and")
            appendLine("ARCHITECTURE.md §17 for what each one owns.")
            appendLine()
            appendLine("## Package → module")
            appendLine()
            appendLine("| Package | Module(s) |")
            appendLine("|---|---|")
            pkgToModules.forEach { (pkg, mods) ->
                val marker = if (mods.size > 1) " ⚠️" else ""
                appendLine("| `$pkg` | ${mods.joinToString(", ") { "`$it`" }}$marker |")
            }
            appendLine()
            appendLine("## Packages split across modules")
            appendLine()
            if (shared.isEmpty()) {
                appendLine("None — every package lives in exactly one module.")
            } else {
                appendLine("${shared.size} packages live in more than one module (⚠️ above) — opening one by name finds")
                appendLine("only part of it. This should be empty: either move the files together, or give the two")
                appendLine("halves the package name of the module each belongs to.")
                appendLine()
                shared.forEach { (pkg, mods) ->
                    appendLine("- `$pkg` → ${mods.joinToString(", ") { "`$it`" }}")
                }
            }
            appendLine()
            appendLine("## Module → packages")
            appendLine()
            modulePkgs.forEach { (mod, pkgs) ->
                appendLine("### `$mod` (${moduleFiles[mod]} files)")
                appendLine()
                pkgs.forEach { appendLine("- `$it`") }
                appendLine()
            }
        }
        output.parentFile.mkdirs()
        output.writeText(text)
        logger.lifecycle("Wrote ${output.relativeTo(rootDir)}")
    }
}

// The enforcement half of `codeMap`: an import names its module only while every package lives in one module,
// every file sits in the module whose path its package mirrors, and every file's package matches its folder.
tasks.register("codeMapCheck") {
    group = "verification"
    description = "Fails on a split package, a package that does not mirror its module, or a file whose " +
        "declared package disagrees with its directory (see docs/code-map.md)."
    notCompatibleWithConfigurationCache("walks every module's source tree")
    val audit = provider { rootProject.auditPackages(rootProject.sourceFiles()) }
    outputs.upToDateWhen { false }
    doLast {
        val result = audit.get()
        if (result.isClean) {
            logger.lifecycle(
                "codeMapCheck: every package lives in exactly one module, mirrors its module path, and " +
                    "matches its directory."
            )
            return@doLast
        }
        throw GradleException(
            buildString {
                if (result.split.isNotEmpty()) {
                    appendLine("${result.split.size} package(s) live in more than one module — an import no")
                    appendLine("longer names its module. Move the files together, or rename each half after the")
                    appendLine("module it belongs to.")
                    result.split.forEach { (pkg, mods) -> appendLine("  - $pkg -> ${mods.joinToString(", ")}") }
                    appendLine()
                }
                if (result.misplaced.isNotEmpty()) {
                    appendLine("${result.misplaced.size} file(s) declare a package outside the module that holds")
                    appendLine("them. Package path mirrors module path — move the file, or rename the package.")
                    result.misplaced.forEach { appendLine("  - $it") }
                    appendLine()
                }
                if (result.strayed.isNotEmpty()) {
                    appendLine("${result.strayed.size} file(s) declare a package their directory contradicts, so")
                    appendLine("the folder tree stops being a reliable index. Move the file into the folder its")
                    appendLine("package names.")
                    result.strayed.forEach { appendLine("  - $it") }
                }
            }
        )
    }
}

// ----------------------------------------------------------------------------------------------------------
// `./gradlew dependencyDirectionCheck` — every arrow in the module graph points down. This is what replaced
// the deleted LayeringRulesTest: the rules moved from counting imports (which became unwritable) to reading
// the declared project dependencies, which is where the layering actually lives.
//
// A module may depend only on a STRICTLY lower rank. Rank alone cannot express every rule in CLAUDE.md — a
// legal rank pair can still be a forbidden edge (`:platform:android` is deliberately Compose-free even though
// `:core:designsystem` sits below it) — so the bans below carry the rest.

// ----------------------------------------------------------------------------------------------------------
// Portability — the shared source sets stay reachable from every target we might add
// ----------------------------------------------------------------------------------------------------------
//
// Today's targets are `android` and `jvm("desktop")`, and BOTH are JVM — so a stray `java.util.UUID` in a
// commonMain file compiles, ships, and is invisible until the day a non-JVM target is added and hundreds of
// files stop building at once. That day is Kotlin/Native (iOS), and the cost of finding out then is a
// migration; the cost of finding out now is one import.
//
// It is currently clean: every commonMain source set in the tree is free of `java.*`/`javax.*`. This task
// exists to keep it that way, because "clean" is a property nothing else in the build would notice losing.
//
// A JVM-only implementation is not a violation — it just does not belong in commonMain. Two homes for it:
// `src/jvmShared` (one directory wired into androidMain + desktopMain by `aide.kmp.library`) when Android and
// desktop want the same JVM code, or a platform module when they do not.
val portabilityCheck = tasks.register("portabilityCheck") {
    group = "verification"
    description = "Fails on a JVM-only or Android-only import inside a commonMain/commonTest source set — " +
        "the thing that would silently make a future Kotlin/Native target unreachable."
    notCompatibleWithConfigurationCache("walks every module's source tree")
    val offenders = provider {
        val importLine = Regex("""^\s*import\s+((?:java|javax|android)\.[\w.]+)""")
        rootProject.subprojects
            .filter { it.buildFile.exists() }
            .sortedBy { it.path }
            .flatMap { sub ->
                val src = File(sub.projectDir, "src")
                if (!src.isDirectory) return@flatMap emptyList<String>()
                src.walkTopDown()
                    .filter { it.isFile && it.extension == "kt" }
                    .filter { file ->
                        val path = file.invariantSeparatorsPath
                        // Only the source sets EVERY target compiles. `jvmShared`, `androidMain`,
                        // `desktopMain` and friends are JVM on purpose and are none of this task's business.
                        path.contains("/src/commonMain/") || path.contains("/src/commonTest/")
                    }
                    .flatMap { file ->
                        val relative = file.relativeTo(rootDir).invariantSeparatorsPath
                        file.useLines { lines ->
                            lines.mapNotNull { importLine.find(it)?.groupValues?.get(1) }
                                .map { "$relative: imports `$it`" }
                                .toList()
                        }
                    }
                    .toList()
            }
    }
    outputs.upToDateWhen { false }
    doLast {
        val bad = offenders.get()
        if (bad.isEmpty()) {
            logger.lifecycle("portabilityCheck: commonMain is free of java.*/javax.*/android.* — every target can still reach it.")
            return@doLast
        }
        throw GradleException(
            buildString {
                appendLine("${bad.size} shared-source file(s) import a JVM-only or Android-only API. They")
                appendLine("compile today only because both current targets are JVM; a Kotlin/Native target")
                appendLine("would not build at all. Move the implementation to `src/jvmShared` (Android +")
                appendLine("desktop) or to the platform module that owns it, and leave a port behind.")
                bad.forEach { appendLine("  - $it") }
            }
        )
    }
}

val moduleRanks = mapOf(
    // Numbered in TENS on purpose. Dense integers meant inserting one module renumbered everything above
    // it, so the diff that added a module also touched every unrelated line — and a reviewer could not see
    // which edge actually changed. Gaps make an insertion a one-line diff.
    // The portable AI SDK sits below everything: it depends on nothing of ours by design, and :data:llm
    // (60) is what consumes it. Its own submodules land at 15/25/35 as they arrive.
    ":aisdk" to 5,
    ":aisdk:util" to 15,
    ":aisdk:providers" to 25,
    ":aisdk:runtime" to 35,

    ":core:common" to 0,
    ":core:domain" to 10,
    ":core:designsystem" to 20,

    // --- Platform roots. One target's machinery each; two roots never see each other, so they share a
    // --- rank and no order between them is ever needed.
    ":platform:android" to 30,

    // --- The implementation layer. `:data` itself is the thin plumbing every slice shares (the Ktor
    // --- factory, the preference store, the download engine); each slice is a domain, and the slices
    // --- that depend on another slice sit one step higher.
    ":data" to 50,
    ":data:speech" to 55,
    ":data:connector" to 55,
    ":data:tools" to 55,
    ":data:llm" to 60,

    // --- Per-target halves of the seams above.
    ":data:speech:sherpa" to 70,

    ":feature:tasks" to 80,
    ":platform:android:surface:ime" to 100,
    ":ui" to 110,
    ":di" to 120,
    ":app" to 130,
    ":desktopApp" to 130,
    // `:server` shares no code with the app, in either direction; the ban list below is what says so.
    ":server" to Int.MIN_VALUE,
)

/**
 * `from` glob -> `to` glob it may never depend on -> the sentence from CLAUDE.md that says why.
 *
 * Triples rather than a script-declared class on purpose: the task below captures this list, and a build
 * script's own types cannot be serialized into the configuration cache.
 */
val forbiddenEdges: List<Triple<String, String, String>> = listOf(
    Triple(":ui", ":data*", ":ui depends on the ports, never on :data"),
    Triple(":data*", ":core:designsystem", ":data must not inherit the design system"),
    // EXACT, not a prefix: `:platform:android` itself is deliberately Compose-free so the data and tool
    // modules that want its machinery do not inherit the design system. Its CHILDREN are a different
    // matter — `:platform:android:ui` exists precisely to draw, and a surface owns its own UI.
    Triple(":platform:android", ":core:designsystem", ":platform:android is deliberately Compose-free"),
    Triple(":core:common", ":*", ":core:common depends on nothing of ours"),
    Triple(":server", ":*", ":server shares no code with the app"),
    Triple(":*", ":server", ":server shares no code with the app"),
    Triple(":*", ":app", "an application is an entry point; nothing may depend on one"),
    Triple(":*", ":desktopApp", "an application is an entry point; nothing may depend on one"),
)

// `:ui` is the shared UI; only the Koin graph and the two entry points are allowed to see it, which is what
// keeps ":di is the ONLY module that sees both sides" true.
val uiConsumers = setOf(":di", ":app", ":desktopApp")

/**
 * Module trees that depend on nothing of ours: root path -> the sentence that says why.
 *
 * Neither mechanism above can state this. Ranks *permit* the edge — `:aisdk` is 5 and `:core:common` is 0,
 * so `:aisdk:providers -> :core:domain` reads as a perfectly ordinary descent — and a
 * `Triple(":aisdk*", ":*", …)` ban would also outlaw `:aisdk:providers -> :aisdk:util`, which is the
 * library's own internal wiring. So the rule is a closure, not a ban: an `:aisdk*` module may see `:aisdk*`
 * and nothing else. Same glob semantics as the ban list.
 */
val closedTrees: Map<String, String> = mapOf(
    // The whole reason `:aisdk` can target everything Kotlin does — and can one day be published on its own
    // — is that no AIDE type is reachable from it. One `ProviderId` import would end that quietly.
    ":aisdk" to ":aisdk is a portable library; it knows nothing about AIDE",
)

/**
 * The aggregate. The real work happens in a task PER MODULE, contributed below, because that is what lets
 * each one capture its own declared dependencies at configuration time — a root task that reaches across
 * `subprojects` at execution time cannot be stored in the configuration cache at all.
 */
val dependencyDirectionCheck = tasks.register("dependencyDirectionCheck") {
    group = "verification"
    description = "Fails if any module declares a dependency that inverts the layering (see CLAUDE.md)."
}

subprojects {
    afterEvaluate {
        // Skip the path-only container projects (":core", ":data:speech") — no build file, no dependencies,
        // and nothing to rank.
        if (!buildFile.exists()) return@afterEvaluate
        val fromPath = path
        // Captured NOW, as plain strings. Nothing below references the build script or a Project.
        val declared: List<String> = configurations
            // Dokka's aggregation configurations point the DOCS at the modules being documented —
            // a publication edge, not a code dependency, and the one place an "upward" arrow is the
            // whole point (the umbrella module collects its children's pages).
            .filterNot { conf -> conf.name.startsWith("dokka") }
            .flatMap { conf -> conf.dependencies.withType(ProjectDependency::class.java) }
            .map { it.path }
            .filter { it != fromPath }
            .distinct()
            .sorted()
        val ranks: Map<String, Int> = LinkedHashMap(moduleRanks)
        val bans: List<Triple<String, String, String>> = ArrayList(forbiddenEdges)
        val consumersOfUi: Set<String> = LinkedHashSet(uiConsumers)
        val closed: Map<String, String> = LinkedHashMap(closedTrees)

        val moduleCheck = tasks.register("dependencyDirectionCheck") {
            group = "verification"
            description = "Fails if $fromPath declares a dependency that inverts the layering."
            outputs.upToDateWhen { false }
            doLast {
                fun String.matchesGlob(glob: String): Boolean =
                    if (glob.endsWith("*")) startsWith(glob.dropLast(1)) else this == glob

                val violations = mutableListOf<String>()
                val fromRank = ranks[fromPath]
                if (fromRank == null) {
                    violations += "$fromPath is not ranked — add it to moduleRanks in build.gradle.kts"
                }
                declared.forEach { to ->
                    val toRank = ranks[to]
                    when {
                        toRank == null ->
                            violations += "$to is not ranked — add it to moduleRanks in build.gradle.kts"
                        fromRank != null && fromRank <= toRank ->
                            violations += "$fromPath -> $to inverts the graph " +
                                "(rank $fromRank must exceed rank $toRank)"
                    }
                    bans.forEach { (banFrom, banTo, because) ->
                        if (fromPath.matchesGlob(banFrom) && to.matchesGlob(banTo) && fromPath != to) {
                            violations += "$fromPath -> $to is forbidden: $because"
                        }
                    }
                    closed.forEach { (root, because) ->
                        if (fromPath.matchesGlob("$root*") && !to.matchesGlob("$root*")) {
                            violations += "$fromPath -> $to is forbidden: $because"
                        }
                    }
                    if (to == ":ui" && fromPath !in consumersOfUi) {
                        violations += "$fromPath -> :ui is forbidden: only " +
                            "${consumersOfUi.joinToString(", ")} may see the shared UI"
                    }
                }
                if (violations.isEmpty()) {
                    logger.info("dependencyDirectionCheck: $fromPath — ${declared.size} edges, all point down.")
                    return@doLast
                }
                throw GradleException(
                    buildString {
                        appendLine("${violations.size} module dependency violation(s) in $fromPath. The module")
                        appendLine("graph is also the platform-gating mechanism, so an inversion breaks both.")
                        appendLine("See CLAUDE.md 'Module map'.")
                        violations.distinct().forEach { appendLine("  - $it") }
                    }
                )
            }
        }
        dependencyDirectionCheck.configure { dependsOn(moduleCheck) }
    }
}

// ----------------------------------------------------------------------------------------------------------
// `./gradlew schemaCheck` — a persisted-schema edit without a version bump breaks every existing install.
//
// Every `<module>/schemas/` directory is a ledger: version N's file is written once and never again, and a
// schema change shows up as a NEW N+1.json. Two kinds of file live there:
//
//  - Room exported schemas (`schemas/<Database FQN>/N.json`). `fallbackToDestructiveMigration` fires on a
//    MISSING MIGRATION PATH, not on an identity-hash mismatch, so editing an entity while
//    `@Database(version)` stays put throws `Room cannot verify the data integrity` at open. The bump is also
//    what makes the destructive fallback do its job.
//  - Persisted-document schemas (`schemas/documents/<name>/N.json`). A `PersistedDocument` whose shape
//    changes without its `version` moving decodes old bytes as the new shape. Bump `version` in code and let
//    `PersistedDocumentSchemaTest` write the new N.json.
//
// Either way, a committed N.json that shows up as Modified is the bug.

tasks.register("schemaCheck") {
    group = "verification"
    description = "Fails if a committed schema JSON (Room or persisted document) was rewritten, not versioned."
    notCompatibleWithConfigurationCache("walks every module's schemas/ directory")
    val schemaDirs = provider {
        subprojects.filter { it.buildFile.exists() }
            .map { File(it.projectDir, "schemas") }
            .filter { it.isDirectory }
            .map { it.relativeTo(rootDir).invariantSeparatorsPath }
    }
    val root = rootDir
    outputs.upToDateWhen { false }
    doLast {
        val dirs = schemaDirs.get()
        if (dirs.isEmpty()) return@doLast
        val diff = runCatching {
            val process = ProcessBuilder(listOf("git", "diff", "--name-status", "HEAD", "--") + dirs)
                .directory(root)
                .redirectErrorStream(false)
                .start()
            val text = process.inputStream.bufferedReader().readText()
            if (process.waitFor() != 0) null else text
        }.getOrNull()
        if (diff == null) {
            logger.lifecycle("schemaCheck: no git checkout to compare against — skipped.")
            return@doLast
        }
        val rewritten = diff.lineSequence()
            .mapNotNull { line ->
                val parts = line.split('\t')
                if (parts.size >= 2 && parts[0].startsWith("M") && parts[1].endsWith(".json")) parts[1] else null
            }
            .toList()
        if (rewritten.isEmpty()) {
            logger.lifecycle("schemaCheck: no committed schema file was rewritten.")
            return@doLast
        }
        throw GradleException(
            buildString {
                appendLine("${rewritten.size} committed schema file(s) were rewritten in place:")
                rewritten.forEach { appendLine("  - $it") }
                appendLine()
                appendLine("Version N's schema file is written once and never edited. Add N+1 instead:")
                appendLine()
                appendLine("  Room (schemas/<Database>/N.json): bump `@Database(version = N + 1)` and let KSP")
                appendLine("  write the new N.json. Room's destructive fallback only fires on a missing")
                appendLine("  migration PATH — at the same version it throws `IllegalStateException: Room")
                appendLine("  cannot verify the data integrity` on every existing install.")
                appendLine()
                appendLine("  Persisted document (schemas/documents/<name>/N.json): bump the document's")
                appendLine("  `PersistedDocument.version` in code and let `PersistedDocumentSchemaTest` write")
                appendLine("  the new N.json.")
                appendLine()
                appendLine("Then restore the old file(s):")
                appendLine("  git checkout -- ${rewritten.joinToString(" ")}")
            }
        )
    }
}

// ----------------------------------------------------------------------------------------------------------
// Static analysis. There was none: no detekt, no ktlint, no lint config. Applied to every module from here
// (rather than a line in 22 build files) with ONE curated ruleset — see config/detekt/detekt.yml for why the
// style rulesets are off and the defect-shaped ones are on.

subprojects {
    // Not :server. Spring's dependency-management plugin applies its BOM to EVERY configuration, detekt's
    // included, which drags the project's Kotlin onto detekt's own classpath — and detekt 1.23 refuses to
    // run against a Kotlin it was not compiled with. `resolutionStrategy.force` does not win against that
    // BOM. It costs little: :server is a 165-line service that shares no code with the app, and it has its
    // own compiler strictness (-Xjsr305=strict) plus Spring's own analysis.
    if (path == ":server") return@subprojects
    apply(plugin = "io.gitlab.arturbosch.detekt")
    extensions.configure<io.gitlab.arturbosch.detekt.extensions.DetektExtension> {
        config.setFrom(rootProject.layout.projectDirectory.file("config/detekt/detekt.yml"))
        buildUponDefaultConfig = true
        parallel = true
        // Every source set, including tests: a swallowed cancellation in a test fixture is still a defect.
        source.setFrom(files("src"))
    }
    // detekt runs on its OWN Kotlin, not the project's. Without this, `:server` fails outright — Spring's
    // dependency-management plugin applies its BOM to every configuration, including detekt's, and detekt
    // refuses to run against a Kotlin version it was not compiled with.
    tasks.withType<io.gitlab.arturbosch.detekt.Detekt>().configureEach {
        jvmTarget = "21"
        reports {
            html.required.set(true)
            xml.required.set(false)
            sarif.required.set(false)
            txt.required.set(false)
            md.required.set(false)
        }
    }
}

/** Every module's detekt, as one task — `aideCheck` depends on it. */
val detektAll = tasks.register("detektAll") {
    group = "verification"
    description = "Runs detekt over every module."
    dependsOn(subprojects.map { it.tasks.matching { task -> task.name == "detekt" } })
}

// ----------------------------------------------------------------------------------------------------------
// The two aggregates the Makefile and CI both call. Naming the task list ONCE here is the point: a module
// whose tests exist but are missing from a hand-kept list is exactly the failure `:app:testReleaseUnitTest`
// was — a green step that ran nothing.

/**
 * The four aisdk modules' BCV apiCheck, as one task. Fixed paths, not a matcher: a matcher that
 * finds nothing goes green silently, where a missing path fails configuration loudly.
 */
val aisdkApiCheck = tasks.register("aisdkApiCheck") {
    group = "verification"
    description = "Verifies the committed ABI dumps of the aisdk modules (Kotlin ABI validation)."
    dependsOn(
        ":aisdk:checkKotlinAbi",
        ":aisdk:util:checkKotlinAbi",
        ":aisdk:providers:checkKotlinAbi",
        ":aisdk:runtime:checkKotlinAbi",
    )
}

val aisdkApiDump = tasks.register("aisdkApiDump") {
    group = "other"
    description = "Regenerates the aisdk ABI dumps after a deliberate API change (commit the diff)."
    dependsOn(
        ":aisdk:updateKotlinAbi",
        ":aisdk:util:updateKotlinAbi",
        ":aisdk:providers:updateKotlinAbi",
        ":aisdk:runtime:updateKotlinAbi",
    )
}

tasks.register("aideCheck") {
    group = "verification"
    description = "Typechecks every target and enforces the structural invariants (module graph, packages, schemas)."
    dependsOn(
        ":app:compileDebugKotlin",
        ":desktopApp:compileKotlin",
        ":server:compileKotlin",
        "codeMapCheck",
        "portabilityCheck",
        "dependencyDirectionCheck",
        "schemaCheck",
        "aisdkApiCheck",
        // Android Lint on the debug variant. It used to run only at TAG TIME, on `lintRelease` with no
        // baseline — so the manifest-class bug fixed in 655ef2c was catchable during a release and nowhere
        // else. A lint that runs on every check is the point.
        ":app:lintDebug",
        "detektAll",
        // The desktop Koin graph test: a missing binding is not a compile error, so typechecking alone
        // cannot tell you the app still starts.
        ":desktopApp:test",
    )
}

tasks.register("aideTest") {
    group = "verification"
    description = "Runs every host test task in the build (:server excluded — `make server-test` needs Docker)."
    // A live collection, so a module that gains its first test is picked up without editing this file.
    // Release variants are skipped: they run the same sources as debug for twice the wall clock.
    dependsOn(
        subprojects
            .filter { it.path != ":server" }
            .map { sub ->
                sub.tasks.withType(Test::class.java).matching { !it.name.contains("Release", ignoreCase = true) }
            }
    )
}
